# Generated by Django 4.1.2 on 2023-11-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_news_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="publication_date",
            field=models.CharField(max_length=255),
        ),
    ]
