name: Deploy
  
on:
  push:
    branches:
          - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
    steps: 
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@main
      with:
        host: 164.90.214.44
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/django_deploy_app/myproject
          git pull origin main
          # Add other commands as needed


