name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
            python -m pip install django
            python manage.py test

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 164.90.214.44
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /root/django_deploy_app/myproject
            source /root/venv/bin/activate
            git pull
            python manage.py migrate
            python manage.py collectstatic --noinput
            supervisorctl restart all



