name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 164.90.214.44
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /root/django_deploy_app/myproject
          git pull origin master  # Пример команды, чтобы получить изменения из репозитория
          # Добавь другие команды, которые нужно выполнить на сервере после обновления кода

         


